-- Create tables
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS player_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  address TEXT UNIQUE NOT NULL,
  username TEXT,
  avatar_url TEXT,
  team_id BIGINT REFERENCES teams(id),
  score INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed teams data
-- First delete player profiles from teams being removed
DELETE FROM player_profiles WHERE team_id IN (
  SELECT id FROM teams WHERE name IN ('Phoenix', 'Hermes', 'Goliath')
);

-- Then delete the teams
DELETE FROM teams WHERE name IN ('Phoenix', 'Hermes', 'Goliath');

INSERT INTO teams (name, description, image_url) VALUES
  ('My Pen Is Long', 'Bold and creative', 'https://api.dicebear.com/7.x/avataaars/svg?seed=MyPenIsLong'),
  ('Thousand Monkeys Thousand Typewriters', 'Infinite possibilities', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ThousandMonkeys'),
  ('Wrapsynth', 'Synthesizing solutions', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Wrapsynth'),
  ('Bebop', 'Rhythmic and smooth', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bebop'),
  ('Golti Bros', 'Brothers in arms', 'https://api.dicebear.com/7.x/avataaars/svg?seed=GoltiBros'),
  ('PizzaBlitz', 'Fast and delicious', 'https://api.dicebear.com/7.x/avataaars/svg?seed=PizzaBlitz'),
  ('Sergei Chain.Love', 'Blockchain devotees', 'https://api.dicebear.com/7.x/avataaars/svg?seed=SergeiChainLove'),
  ('MarcoPolo', 'Navigation experts', 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarcoPolo'),
  ('moonmono', 'Lunar vibes', 'https://api.dicebear.com/7.x/avataaars/svg?seed=moonmono'),
  ('Arrive', 'Always on time', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arrive'),
  ('Trust Me Bro', 'Confident and bold', 'https://api.dicebear.com/7.x/avataaars/svg?seed=TrustMeBro'),
  ('Tharun Ekambaram', 'Individual force', 'https://api.dicebear.com/7.x/avataaars/svg?seed=TharunEkambaram'),
  ('CPL', 'Compact and powerful', 'https://api.dicebear.com/7.x/avataaars/svg?seed=CPL'),
  ('EthKiller', 'Ethereum warriors', 'https://api.dicebear.com/7.x/avataaars/svg?seed=EthKiller'),
  ('Pizza Rush', 'Quick delivery team', 'https://api.dicebear.com/7.x/avataaars/svg?seed=PizzaRush'),
  ('sexy', 'Attractive results', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sexy'),
  ('$BLUFF', 'High stakes', 'https://api.dicebear.com/7.x/avataaars/svg?seed=BLUFF'),
  ('BuzzBallz Enjoyers', 'Party team', 'https://api.dicebear.com/7.x/avataaars/svg?seed=BuzzBallz'),
  ('DVB HyperStream', 'Streaming success', 'https://api.dicebear.com/7.x/avataaars/svg?seed=DVBHyperStream'),
  ('The Last Slice', 'Final champions', 'https://api.dicebear.com/7.x/avataaars/svg?seed=TheLastSlice'),
  ('Solo', 'Independent spirit', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Solo'),
  ('Formula Zero', 'Zero defects', 'https://api.dicebear.com/7.x/avataaars/svg?seed=FormulaZero'),
  ('upsilon', 'Greek strength', 'https://api.dicebear.com/7.x/avataaars/svg?seed=upsilon'),
  ('Team Boston', 'East coast pride', 'https://api.dicebear.com/7.x/avataaars/svg?seed=TeamBoston'),
  ('Friday', 'Weekend vibes', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Friday'),
  ('Mace', 'Medieval power', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mace')
ON CONFLICT (name) DO NOTHING;

-- Drop existing policies (if any)
DROP POLICY IF EXISTS "public_insert_profiles" ON player_profiles;
DROP POLICY IF EXISTS "public_select_profiles" ON player_profiles;
DROP POLICY IF EXISTS "public_update_profiles" ON player_profiles;
DROP POLICY IF EXISTS "public_select_teams" ON teams;

-- Enable RLS
ALTER TABLE player_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

-- Create new policies
CREATE POLICY "public_select_profiles" ON player_profiles FOR SELECT USING (true);
CREATE POLICY "public_insert_profiles" ON player_profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "public_update_profiles" ON player_profiles FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "public_select_teams" ON teams FOR SELECT USING (true);

-- Optional performance index
CREATE INDEX IF NOT EXISTS idx_player_profiles_team_id ON player_profiles(team_id);
