export const PREDICTION_MARKET_ABI = [
  {
    type: 'function',
    name: 'getTeamCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getTeamInfo',
    stateMutability: 'view',
    inputs: [{ name: 'teamId', type: 'uint256' }],
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'totalBets', type: 'uint256' },
      { name: 'bettorCount', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'placeBet',
    stateMutability: 'payable',
    inputs: [{ name: 'teamId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimWinnings',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resolveMarket',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_winningTeamId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'addTeam',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'name', type: 'string' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'resolved',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'totalPot',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'winningTeamId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'bets',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'teamId', type: 'uint256' },
      { name: 'multiplier', type: 'uint256' },
    ],
  },
] as const;
